### ISSUE TITLE
[Questions] Status and more

### ISSUE THREAD

**Issue by ablekh** [kevinwojo/hz-project-chat#1]
Hi Kevin,

Hope you're doing well. What is the status of this effort? Is it planned to be integrated into the upstream? If Yes, what is the approximate timeline? If No, is the implementation complete, so that we could try to install this as a Projects plugin? If so, any specific installation instructions? Please advise.

I am also curious about your hub-in-a-box repo (cool - I have thought about implementing the Ansible playbooks-based approach and found your implementation). Is it fully compatible with the upstream? Having said that, we also explore the upstream repo-based installation (instead of package-based) - any potential issues we need to know about? For example, what is the optimal way to ensure compatibility with relevant internal (e.g., Maxwell, submit) and external (e.g., Pegasus) packages distributed as such?

Thank you,
Aleks

**Comment by kevinwojo** [comment]
The hz-project-chat was a placeholder for an idea I would like to implement in my free time. It's not implemented and there is no timeline for completion. 

The Ansible playbook that I've developed uses the HUBzero RedHat Packages to build an "open source" hub, which is as close to our structure minus the CMS's pulling directly from our internal git repositories. 

We use git internally because we do development on our hosted hub for code that does not get contributed back into core and the open source release. 

I still maintain that our packages is the best and most reliable way to keep HUBzero dependencies in-sync. We do not have a mechanism for patching with our CMS on Github. We rely internally on our configuration management, which may or may not be replaced with Ansible.

We do plan to put all repositories for all current HUBzero services on Github such as Maxwell and Submit, and the rest. We do not have a timeline for that, however.

**Comment by ablekh** [comment]
Thank you, Kevin! I appreciate your detailed reply. Just wanted to clarify: do I understand correctly that all of the code appearing in HZ GitHub repo does get included into the official open source releases (packages)?

**Comment by kevinwojo** [comment]
The code in hubzero-cms and framework on github is packaged. We tend to lag about a week or so in order to package the patches of issues we discover by deploying out to our production environment. We push code out to our production hosts once a month (usually on the first Sunday of the month). Then we have a week of hot-fixing. Those hotfixes are then incorporated into the package published about a week later.

We hope to increase the frequency of package updates for all HUBzero code.

**Comment by ablekh** [comment]
Understood. Thanks a lot for clarification and prompt replies! :-)

P.S. A suggestion: please refactor the CMS codebase, if possible, so that _overriding_ components, plugins etc. in the template code would require no copying of any **extra** files from the **core**. I hope that it is feasible.
